### ISSUE TITLE
Consider merging with an existing list

### ISSUE THREAD

**Issue by Jogai** [paulaime/awesome-privacy#9]
It looks like @KevinColemanInc's list (https://github.com/KevinColemanInc/awesome-privacy) exists longer. Why not contribute to that?

See also https://github.com/pluja/awesome-privacy/issues/24

**Comment by paulaime** [comment]
Most privacy lists I found on GitHub were rather limited (few categories), so that's why I decided to create a broader and more diverse list with software of all horizons (graphic design, video editing, web development, mobile security…).
But why not merge with other lists in the future if they're interested.
